apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webconsumer-node
  name: webconsumer-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webconsumer-node
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webconsumer-node
    spec:
      containers:
      - image: simonanderson/webconsumer
        name: webconsumer
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webconsumer-node
  name: webconsumer-node
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: webconsumer-node
  type: ClusterIP
status:
  loadBalancer: {}
