apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webconsumer
  name: webconsumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webconsumer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webconsumer
    spec:
      containers:
      - image: simonanderson/webconsumer
        name: webconsumer
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webconsumer
  name: webconsumer
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: webconsumer
  type: ClusterIP
status:
  loadBalancer: {}
